." Manpage for backupuser
.".RI [ underlined ]
.TH backupuser 1 "October 2020" "backupuser 1.1" "Manpage for backupuser"
.SH NAME
backupuser \- User backup utility
.SH SYNOPSIS
.BR "backupuser " "[-hijkpruvx] [-d BACKUP] [-s SCP_DESTINATION] [local_disks]"
.br
.BR "backupuser " "[-v] [-s SCP_DESTINATION] etc [local_disks]"
.br
.BR "backupuser " "clean"
.SH DESCRIPTION
backupuser is a shell script utility, that allows a user to create backups of his home directory. These backups are placed in subdirectories of ${HOME}/backups ordered by year. All other non-option arguments, that are passed to backupuser upon invocation, will be treated as external storage devices and the utility will attempt to copy the backup to the given arguments.

Any scripts, that may reside in the folder ${HOME}/.bu, will be processed in pre- and post-backup stages when being prefixed with the words 'pre' and 'post' respectively. If the special file ${HOME}/.bu/bu_excludes exists, then any files and folders mentioned in this file will not be backed up. To be excluded, files and folders should be specified with their full path to file. In case the argument "clean" is passed to the utility upon invocation, then backupuser will clean the user's backup directory ${HOME}/backups. The following special options exist for root: Passing "etc" as a command, causes the utility to generate a backup of the system's /etc directory.

When copying the backup to external storage, backupuser's accompanying utility, \fBbu_check_files(1)\fR, can be used to generate a fresh reportfile on that drive in order to subsequently verify the integrity of the backups with the \fBdiff(1)\fR utility.

.SH OPTIONS
.TP
.B -d BACKUP
delete the backup BACKUP and exit. The respective entry in the reportfile will also be deleted if it exists.
.TP
.B -h
create the archive directly in the destination directory instead of going via /tmp. This can be useful on systems where /tmp is not available to the user.
.TP
.B -i
ignore the pre- and post-backup stages.
.TP
.B -j
do not process the pre-backup stage.
.TP
.B -k
do not process the post-backup stage.
.TP
.B -p
generate a list of installed packages/ports in ${HOME} (root only).
.TP
.B -r
do not log the backup in reportfile.
.TP
.B -s SCP_DESTINATION
copy the backup via secure shell to SCP_DESTINATION.
.TP
.B -u
print usage information and exit.
.TP
.B -v
be more verbose.
.TP
.B -x
ignore the file bu_excludes if it exists.
.SH EXAMPLES
.PP
1. Backup ${HOME} and copy the backups to external storage devices "storage1" and "storage2" respectively:
.PP
backupuser -v /path/to/external/storage1 /path/to/external/storage2
.PP
2. Backup ${HOME} and copy the backup to an external server via SSH:
.PP
backupuser -v -s "-p 2222 user@server.com:/path/to/file"
.PP
3. Clean the user's backup directory ~/backups:
.PP
backupuser clean
.PP
4. Create a backup of the /etc directory as the root user:
.PP
backupuser etc
.SH BUGS
Please report when found.
.SH SEE ALSO
bu_check_files(1)
.SH AUTHOR
Oliver Mahmoudi (contact@olivermahmoudi.com)
