#!/bin/sh

# Copyright (c) 2015-2017 Oliver Mahmoudi
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions 
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Place this script in the folder to which you copy your backups and run it
# to:
# 	a) check the files for errors via gzip --test and 
# 	b) generate their checksums.
# 
# Later, the generated report file can be diffed with the original report file 
# on the users hard drive.
# 

### variables
USER=$(whoami)
REPORT_FILE=${USER}_report.txt
CONTENTS=$(ls *.tar.gz)
OS_TYPE=$(uname)

### entry point
: > ${REPORT_FILE}				# create a fresh report file

for i in ${CONTENTS} ; do
	gzip --test ${i} > /dev/null 2>&1
	if [ $? -eq 0 ] ; then
	# Checksums
		if [ "${OS_TYPE}" = "Linux" ] ; then
			sha256sum ${i} >> ${WHO}_report.txt		# Linux uses the sha256sum command
		elif [ "${OS_TYPE}" = "FreeBSD" ] ; then
			sha256 ${i} >> ${WHO}_report.txt		# FreeBSD uses sha256
		fi
	else
		echo "File: ${i} is corrupted." >> ${REPORT_FILE}
	fi
done

echo "Done"'!'

exit 0
